### ISSUE TITLE
Calculus does not provide an export mechanism for the answer

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#10]
This is an **Enhancement** request.

Use case: The user generates a result with Calculus and wants to incorporate it into a document. It would be useful to include an export button to save the equation as a PNG, SVG, RTF, HTML or  LaTeX equation to facilitate this. As it stands the user will have to manually transcribe the result from Calculus. Or take a screenshot.

**Comment by carlos157oliveira** [comment]
It will take me a while before i can work on this. It is a good suggestion.

**Comment by carlos157oliveira** [comment]
I got some time today. The changes should be present in _master_ branch. I will not release it yet, there is something that I would like to change first and see if it improves application performance.

**Comment by carlos157oliveira** [comment]
Soon a new version will be in Flathub. Would you like to test it?

**Comment by johnblommers** [comment]
Yes I will test it. I see Calculus 1.4.1 is already up on Flathub with new features:

- Open result in separate window
- Export result as LaTeX code
- Implemented multiprocessing for result computation

**Comment by johnblommers** [comment]
Opening the result in a separate window works as advertised. But when the resulting equation is wide, the plot window doesn't how the entire result. Indeed the plot window saves the current view. Since you want the entire formula  captured you have to widen the plot window manually before saving the result. 

In this situation a screen shot from the parent window is the better solution. **<kbd>Alt</kbd> <kbd>Prt Sc</kbd>** is capable of capturing all of a window's contents even those portions currently off screen. At least on GNOME 3.

Export to LaTeX code on clipboard works very neatly indeed. That's perfect actually since now the result can be pasted between two dollar signs in Markdown documents.

I'm not sure how to test the multiprocessing feature.

**Comment by carlos157oliveira** [comment]
I have tried to configure the plot window in order to fit the result. The configuration didn't work... (it can be changed, but the matplotlib window makes some modifications and changes the resolution in an unexpected way). We could have a option to export direct to _png_, without using that plot window.
The multiprocessing feature is a bit fancy. An application of this size wouldn't need it (before it already had multithreading). If all computations are being done as before (or faster), then we got it properly.

**Comment by johnblommers** [comment]
Adding an option to export directory to PNG should satisfy any user not wishing to leverage LaTeX output.

Out of curiosity, have you found an example where differentiation or integration takes a fair amount of  time? Do those examples demonstrate the benefits of multiprocessing I wonder?

**Comment by carlos157oliveira** [comment]
I didn't take any real benchmark, but some expressions like _e^-x^2_ seem to be a little faster to integrate (although it doesn't have a real primitive).

**Comment by carlos157oliveira** [comment]
Now we have an option to export directly to PNG. Would you like to see if it fits your demands?

**Comment by johnblommers** [comment]
Perfect. But I must have transmitted in the wrong  tone. 

The issues I reported were not meant as making demands. That's too harsh and it's not the tone I mean to transmit.

I honestly want Calculus to be as good as it can be. My suggestion to have Calculus export a PNG was intended in the most positive manner to help make Calculus truly useful to the intended audience.

When I find an interesting and useful open source project I am motivated to offer suggestions. Perhaps I find a bug or feel an enhancement is appropriate. So I write up an issue for consideration. It is always up to the developer to consider them, to determine if they want to adopt, back burner or even set aside the suggestion. This is my way of contributing back to the community.

**Comment by carlos157oliveira** [comment]
Perhaps I was misunderstood, I use the word "demanda" (portuguese) to express "necessity" or a "wish". I used the english one "demand" without thinking it couldn't be good for the context. I was trying to be a little poetical, which isn't good for this technical context.

**Comment by carlos157oliveira** [comment]
Shall we close this issue?

**Comment by johnblommers** [comment]
Absolutely no worries about the use of  the word "demands." It gave me a chance  to explain why I participate as I do in open source projects. All good. I think I was being overly sensitive as well, and it was me who misunderstood :-)

Yes this issue is resolved so please feel free  to close it out.

**Comment by carlos157oliveira** [comment]
Thank you very much for your contributions.
