### ISSUE TITLE
Unclear Error "Displaying result error"

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#11]
I wanted to evaluate the integral of `x^140/(x-1)^140` and after a little while Calculus stopped thinking and opened a little dialog box entitled **Warning** with the message "Displaying result error." That information does not offer me any idea what may be the problem: Could it mean:

- Is the answer too long to display? If so, just say so.
- Did the underlying solver code terminate with an error. If so return the exact error message.
- Is this a generic error message not yet instrumented. It appears pretty generic.
- Is this some kind of bug or limitation of Calculus?

**Comment by carlos157oliveira** [comment]
The message was intended to mean an error with display phase of the process (the computation was successfully). It should mean that matplotlib doesn't fully interpret the LaTeX code generated. One could still be able to export as LaTeX code.

**Comment by johnblommers** [comment]
I just tried again and sure enough the LaTeX code is correct and can be sent to the clipboard. Excellent!

**Comment by carlos157oliveira** [comment]
I am thinking in substitute "Displaying result error" for "Graphical visualization error. The result can still be exported as LaTeX in the menu."

**Comment by johnblommers** [comment]
How about "Matplotlib is unable to render the output. You can still export the output as LaTeX in the menu."

**Comment by carlos157oliveira** [comment]
I will use your phrase. It is pretty good in letting the user know what is happening without complicating it too much.
