### ISSUE TITLE
Calculus needs an About Box

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#12]
Please add to the menu system for Calculus an "About" selection so we know:

- This is Calculus
- Quick summary of its feature set
- Version number and date
- Home page URL
- Names of the developers
- List of open source packages leveraged
- Licence information (GPL, MIT, Apache ...)

This came up because I wanted to find the Calculus home page. But Calculus is such a common name that I wasn't able to find it. Luckily I could search inside my search history and found it there.

**Comment by carlos157oliveira** [comment]
There is a section for _documenters_  in the GTK widget for About dialogs. I would like to put a reference to you there. If you accept, what should be written?

**Comment by johnblommers** [comment]
Cool. How about simply:

Usability and testing: John Blommers

**Comment by carlos157oliveira** [comment]
A new version of Calculus is being published. I was waiting to see if some translations would get updated in time, but it seems to take longer than what I was expecting. Don't forget to tell me if all the data is present there :smile:.
