### ISSUE TITLE
Result plot is empty for integral of 1/sin(x)

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#14]
When the user plots the result of integrating 1/sin(x) the lower plot is empty.

![Screenshot from 2020-12-01 18-46-09](https://user-images.githubusercontent.com/8484427/100821958-419a2000-3406-11eb-9884-06bbf22b65ce.png)

**Comment by carlos157oliveira** [comment]
I have noticed something peculiar in the integrated expression. The argument to the first _log_ will always be equal or less than 0, which would be numerically invalid. I don't know how to prevent these cases by the moment.

**Comment by johnblommers** [comment]
Agreed.

My thinking is that it's not a problem with Calculus. If one drops to the command line and runs Symply directly you get the same kind of thing. It seems like Matplotlib has its issues with it.

On the on the other hand 1/sin(x) is real so one expects the area under the curve to be real as well. But Sympy "knows better" and offers a complex-valued solution.

The problem is with Matplotlib not with Calculus. It's showing what Matplotlib gave to it.

**Comment by carlos157oliveira** [comment]
If I come across an idea (but I'm doubting), I will do something to remediate this. However, in the current time, this will not be worked on. Feel free to open new issues, though.
