### ISSUE TITLE
sin(x*x) integral is wrong

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#18]
Enter sin(x*x), operation variable x, Integrate, and Operate gives nonsense results. This is the LaTeX export out of Calculus:

$\frac{3 \sqrt{2} \sqrt{\pi} S\left(\frac{\sqrt{2} x}{\sqrt{\pi}}\right) \Gamma\left(\frac{3}{4}\right)}{8 \Gamma\left(\frac{7}{4}\right)}$

Calculus is therefore unable to plot the result.

Another example is the integral of exp(x*x) which results in

$\frac{\sqrt{\pi} \operatorname{erfi}{\left(x \right)}}{2}$

This is version 1.5.2 downloaded using Flatpak and running on PopOS 22.04.

**Comment by carlos157oliveira** [comment]
Hi John. Good to see you again! This part is very dependent on the SymPy library. Perhaps the results are right but are presented in an awkward way. If I remember correctly, the integrals you are trying to plot don't have simple primitives, so the library is just translating them, looking for known symbols that represent integrals that also don't have a primitive.

**Comment by johnblommers** [comment]
Your answer is factually correct. To confirm this I even asked [**ChatGPT**](https://chat.openai.com/chat) for shits and giggles and it replied thus:

``The integral of sin(x^2) with respect to x does not have a closed-form solution in terms of standard mathematical functions. This means that it cannot be expressed using a combination of arithmetic operations, exponentials, logarithms, and common mathematical functions such as trigonometric functions or polynomials.

However, it can be expressed in terms of special functions such as the Fresnel integral or the error function. These functions are not as well-known as the standard mathematical functions, but they can be used to represent the solution to certain types of integrals that do not have closed-form solutions in terms of standard functions.

For example, the integral of sin(x^2) with respect to x can be expressed as:

∫ sin(x^2) dx = (1/2) ∫ cos(t^2) dt = (1/2) (S(x^2) + C(x^2)) + C

where S(x) and C(x) are the Fresnel integrals and C is a constant of integration. The Fresnel integrals are defined as:

S(x) = ∫ cos(π/2 t^2) dt
C(x) = ∫ sin(π/2 t^2) dt

These integrals cannot be expressed in terms of standard mathematical functions, but they can be evaluated numerically using special functions provided by many mathematical software packages.

Alternatively, the integral of sin(x^2) with respect to x can also be expressed in terms of the error function, denoted by erf(x). The error function is defined as:

erf(x) = (2/√π) ∫ e^(-t^2) dt

Using this definition, the integral of sin(x^2) with respect to x can be expressed as:

∫ sin(x^2) dx = (1/2) ∫ cos(t^2) dt = (1/2) (erf(x√(π/2)) + C)

where C is a constant of integration.

It's worth noting that these special functions are often used to represent the solutions to certain types of integrals that do not have closed-form solutions in terms of standard mathematical functions, but they are not as widely known or used as the standard functions.

**Comment by carlos157oliveira** [comment]
Thank you for helping me to confirm this!
