### ISSUE TITLE
Location of documentation page

### ISSUE THREAD

**Issue by kd2flz** [carlos157oliveira/Calculus#6]
Hi, sorry if this is a stupid question, but which file is https://carlos157oliveira.github.io/Calculus/ based off? I assumed it would be using the README, but it clearly isn't. 
Thanks a lot!

**Comment by carlos157oliveira** [comment]
I have created a branch called **gh-pages**. The documentation is **index.md**.

**Comment by kd2flz** [comment]
Cool, found it.
________________________________
