### ISSUE TITLE
Unable to save plots

### ISSUE THREAD

**Issue by johnblommers** [carlos157oliveira/Calculus#9]
Calculus distributes as a Flatpak and is boxed. But the sandbox configuration as shipped prevents Calculus from writing to the file system.  The user can quickly work around this by downloading and running [Flatseal](https://github.com/tchx84/flatseal) to configure Calculus with permission to write to the user's home directory like this:

![Screenshot from 2020-11-21 13-07-25](https://user-images.githubusercontent.com/8484427/99887685-0ecc7c80-2bfb-11eb-8903-69185999cd0d.png)

This switch was off before.

**Comment by carlos157oliveira** [comment]
I have added _--filesystem=home_ permission to the manifest file. It should work by default now.

**Comment by johnblommers** [comment]
Sure enough the update appeared in the Pop Shop and Calculus can now save plots to my home directory.

Issue resolved.

**Comment by carlos157oliveira** [comment]
Thank you again. Have a great night and do report bugs when you want.
